// export const COMMUNITY_CHAT = "COMMUNITY_CHAT";
// export const USER_CONNECTED = "USER_CONNECTED";
// export const MESSAGE_RECIVED = "MESSAGE_RECIVED";
// export const MESSAGE_SENT = "MESSAGE_SENT";
// export const USER_DISCONECTED = "USER_DISCONECTED";
// export const TYPING = "TYPING";
// export const VERIFY_USER = "VERIFY_USER";
// export const LOGOUT = "LOGOUT";

module.exports = {
  COMMUNITY_CHAT: "COMMUNITY_CHAT",
  USER_CONNECTED: "USER_CONNECTED",
  MESSAGE_RECIVED: "MESSAGE_RECIVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  TYPING: "TYPING",
  USER_DISCONECTED: "USER_DISCONECTED",
  VERIFY_USER: "VERIFY_USER",
  LOGOUT: "LOGOUT"
};
